// Code generated by protoc-gen-go.
// source: value_api.proto
// DO NOT EDIT!

/*
Package valueproto is a generated protocol buffer package.

It is generated from these files:
	value_api.proto

It has these top-level messages:
	EmptyMsg
	WriteRequest
	LookupRequest
	ReadRequest
	DeleteRequest
	WriteResponse
	LookupResponse
	ReadResponse
	DeleteResponse
*/
package valueproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()         { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()    {}

type WriteRequest struct {
	KeyA  uint64 `protobuf:"varint,1,opt,name=keyA" json:"keyA,omitempty"`
	KeyB  uint64 `protobuf:"varint,2,opt,name=keyB" json:"keyB,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Tsm   int64  `protobuf:"varint,4,opt,name=tsm" json:"tsm,omitempty"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}

type LookupRequest struct {
	KeyA uint64 `protobuf:"varint,1,opt,name=keyA" json:"keyA,omitempty"`
	KeyB uint64 `protobuf:"varint,2,opt,name=keyB" json:"keyB,omitempty"`
	Tsm  int64  `protobuf:"varint,3,opt,name=tsm" json:"tsm,omitempty"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}

type ReadRequest struct {
	KeyA uint64 `protobuf:"varint,1,opt,name=keyA" json:"keyA,omitempty"`
	KeyB uint64 `protobuf:"varint,2,opt,name=keyB" json:"keyB,omitempty"`
	Tsm  int64  `protobuf:"varint,3,opt,name=tsm" json:"tsm,omitempty"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}

type DeleteRequest struct {
	KeyA uint64 `protobuf:"varint,1,opt,name=keyA" json:"keyA,omitempty"`
	KeyB uint64 `protobuf:"varint,2,opt,name=keyB" json:"keyB,omitempty"`
	Tsm  int64  `protobuf:"varint,3,opt,name=tsm" json:"tsm,omitempty"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

type WriteResponse struct {
	Tsm int64  `protobuf:"varint,1,opt,name=tsm" json:"tsm,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}

type LookupResponse struct {
	Tsm    int64  `protobuf:"varint,1,opt,name=tsm" json:"tsm,omitempty"`
	Length uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Err    string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}

type ReadResponse struct {
	Tsm   int64  `protobuf:"varint,1,opt,name=tsm" json:"tsm,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}

type DeleteResponse struct {
	Tsm int64  `protobuf:"varint,1,opt,name=tsm" json:"tsm,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

func init() {
	proto.RegisterType((*EmptyMsg)(nil), "valueproto.EmptyMsg")
	proto.RegisterType((*WriteRequest)(nil), "valueproto.WriteRequest")
	proto.RegisterType((*LookupRequest)(nil), "valueproto.LookupRequest")
	proto.RegisterType((*ReadRequest)(nil), "valueproto.ReadRequest")
	proto.RegisterType((*DeleteRequest)(nil), "valueproto.DeleteRequest")
	proto.RegisterType((*WriteResponse)(nil), "valueproto.WriteResponse")
	proto.RegisterType((*LookupResponse)(nil), "valueproto.LookupResponse")
	proto.RegisterType((*ReadResponse)(nil), "valueproto.ReadResponse")
	proto.RegisterType((*DeleteResponse)(nil), "valueproto.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for ValueStore service

type ValueStoreClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type valueStoreClient struct {
	cc *grpc.ClientConn
}

func NewValueStoreClient(cc *grpc.ClientConn) ValueStoreClient {
	return &valueStoreClient{cc}
}

func (c *valueStoreClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/valueproto.ValueStore/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := grpc.Invoke(ctx, "/valueproto.ValueStore/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/valueproto.ValueStore/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/valueproto.ValueStore/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ValueStore service

type ValueStoreServer interface {
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterValueStoreServer(s *grpc.Server, srv ValueStoreServer) {
	s.RegisterService(&_ValueStore_serviceDesc, srv)
}

func _ValueStore_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ValueStoreServer).Write(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ValueStore_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ValueStoreServer).Lookup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ValueStore_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ValueStoreServer).Read(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ValueStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ValueStoreServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _ValueStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "valueproto.ValueStore",
	HandlerType: (*ValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _ValueStore_Write_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ValueStore_Lookup_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ValueStore_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ValueStore_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
