// Code generated by protoc-gen-go.
// source: ort_api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	ort_api.proto

It has these top-level messages:
	FileRequest
	FileAttr
	File
	WriteResponse
	DirRequest
	DirEntries
	DirEnt
	DirAttr
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type FileRequest struct {
	Fpath string `protobuf:"bytes,1,opt,name=fpath" json:"fpath,omitempty"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto1.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}

// fields are optional by default in proto3, so clients don't have
// to send all fields when performing a attr update for example.
type FileAttr struct {
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mode   string `protobuf:"bytes,3,opt,name=mode" json:"mode,omitempty"`
	Size   uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Mtime  int64  `protobuf:"varint,5,opt,name=mtime" json:"mtime,omitempty"`
}

func (m *FileAttr) Reset()         { *m = FileAttr{} }
func (m *FileAttr) String() string { return proto1.CompactTextString(m) }
func (*FileAttr) ProtoMessage()    {}

type File struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto1.CompactTextString(m) }
func (*File) ProtoMessage()    {}

type WriteResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto1.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}

type DirRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DirRequest) Reset()         { *m = DirRequest{} }
func (m *DirRequest) String() string { return proto1.CompactTextString(m) }
func (*DirRequest) ProtoMessage()    {}

type DirEntries struct {
	Entries []*DirEnt `protobuf:"bytes,1,rep" json:"Entries,omitempty"`
}

func (m *DirEntries) Reset()         { *m = DirEntries{} }
func (m *DirEntries) String() string { return proto1.CompactTextString(m) }
func (*DirEntries) ProtoMessage()    {}

func (m *DirEntries) GetEntries() []*DirEnt {
	if m != nil {
		return m.Entries
	}
	return nil
}

type DirEnt struct {
	Name string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Attr *DirAttr `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *DirEnt) Reset()         { *m = DirEnt{} }
func (m *DirEnt) String() string { return proto1.CompactTextString(m) }
func (*DirEnt) ProtoMessage()    {}

func (m *DirEnt) GetAttr() *DirAttr {
	if m != nil {
		return m.Attr
	}
	return nil
}

type DirAttr struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mode string `protobuf:"bytes,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *DirAttr) Reset()         { *m = DirAttr{} }
func (m *DirAttr) String() string { return proto1.CompactTextString(m) }
func (*DirAttr) ProtoMessage()    {}

// Client API for FileInterface service

type FileInterfaceClient interface {
	GetAttr(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileAttr, error)
	SetAttr(ctx context.Context, in *FileAttr, opts ...grpc.CallOption) (*FileAttr, error)
	Read(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*File, error)
	Write(ctx context.Context, in *File, opts ...grpc.CallOption) (*WriteResponse, error)
}

type fileInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewFileInterfaceClient(cc *grpc.ClientConn) FileInterfaceClient {
	return &fileInterfaceClient{cc}
}

func (c *fileInterfaceClient) GetAttr(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileAttr, error) {
	out := new(FileAttr)
	err := grpc.Invoke(ctx, "/proto.FileInterface/GetAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileInterfaceClient) SetAttr(ctx context.Context, in *FileAttr, opts ...grpc.CallOption) (*FileAttr, error) {
	out := new(FileAttr)
	err := grpc.Invoke(ctx, "/proto.FileInterface/SetAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileInterfaceClient) Read(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := grpc.Invoke(ctx, "/proto.FileInterface/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileInterfaceClient) Write(ctx context.Context, in *File, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/proto.FileInterface/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileInterface service

type FileInterfaceServer interface {
	GetAttr(context.Context, *FileRequest) (*FileAttr, error)
	SetAttr(context.Context, *FileAttr) (*FileAttr, error)
	Read(context.Context, *FileRequest) (*File, error)
	Write(context.Context, *File) (*WriteResponse, error)
}

func RegisterFileInterfaceServer(s *grpc.Server, srv FileInterfaceServer) {
	s.RegisterService(&_FileInterface_serviceDesc, srv)
}

func _FileInterface_GetAttr_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(FileRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FileInterfaceServer).GetAttr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _FileInterface_SetAttr_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(FileAttr)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FileInterfaceServer).SetAttr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _FileInterface_Read_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(FileRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FileInterfaceServer).Read(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _FileInterface_Write_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(File)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(FileInterfaceServer).Write(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _FileInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileInterface",
	HandlerType: (*FileInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttr",
			Handler:    _FileInterface_GetAttr_Handler,
		},
		{
			MethodName: "SetAttr",
			Handler:    _FileInterface_SetAttr_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _FileInterface_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _FileInterface_Write_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for DirInterface service

type DirInterfaceClient interface {
	Create(ctx context.Context, in *DirEnt, opts ...grpc.CallOption) (*WriteResponse, error)
	Remove(ctx context.Context, in *DirEnt, opts ...grpc.CallOption) (*WriteResponse, error)
	Lookup(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirEnt, error)
	ReadDirAll(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirEntries, error)
}

type dirInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewDirInterfaceClient(cc *grpc.ClientConn) DirInterfaceClient {
	return &dirInterfaceClient{cc}
}

func (c *dirInterfaceClient) Create(ctx context.Context, in *DirEnt, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/proto.DirInterface/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirInterfaceClient) Remove(ctx context.Context, in *DirEnt, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/proto.DirInterface/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirInterfaceClient) Lookup(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirEnt, error) {
	out := new(DirEnt)
	err := grpc.Invoke(ctx, "/proto.DirInterface/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dirInterfaceClient) ReadDirAll(ctx context.Context, in *DirRequest, opts ...grpc.CallOption) (*DirEntries, error) {
	out := new(DirEntries)
	err := grpc.Invoke(ctx, "/proto.DirInterface/ReadDirAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DirInterface service

type DirInterfaceServer interface {
	Create(context.Context, *DirEnt) (*WriteResponse, error)
	Remove(context.Context, *DirEnt) (*WriteResponse, error)
	Lookup(context.Context, *DirRequest) (*DirEnt, error)
	ReadDirAll(context.Context, *DirRequest) (*DirEntries, error)
}

func RegisterDirInterfaceServer(s *grpc.Server, srv DirInterfaceServer) {
	s.RegisterService(&_DirInterface_serviceDesc, srv)
}

func _DirInterface_Create_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(DirEnt)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(DirInterfaceServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _DirInterface_Remove_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(DirEnt)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(DirInterfaceServer).Remove(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _DirInterface_Lookup_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(DirRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(DirInterfaceServer).Lookup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _DirInterface_ReadDirAll_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(DirRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(DirInterfaceServer).ReadDirAll(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _DirInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DirInterface",
	HandlerType: (*DirInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DirInterface_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DirInterface_Remove_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _DirInterface_Lookup_Handler,
		},
		{
			MethodName: "ReadDirAll",
			Handler:    _DirInterface_ReadDirAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
